# Base of workflow from [this medium article](https://medium.com/@toufik.airane/automerge-github-dependabot-alerts-with-github-actions-7cd6f5763750)
# According to this [issue](https://github.com/dependabot/feedback/issues/134) if the repo contains the labels "major", "minor", "patch" then Dependabot will automatically label PRs.

name: Dependabot

on:
  pull_request:
    types: [labeled]

jobs:
  auto-merge:
    name: Merge PRs labelled with Minor or Patch
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]' && (contains(github.event.pull_request.labels.*.name, 'minor') || contains(github.event.pull_request.labels.*.name, 'patch'))

    steps:
      - name: Merge if labels exist
        uses: actions/github-script@e2ddba4dfcf622c123222f25bce0589fa3d1d493
        with:
          script: |
            github.issues.createComment({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.pull_request.number,
              body: '@dependabot merge'
            })
          github-token: ${{ secrets.TOKEN_FOR_GUTHUB_ACTIONS_BOT }}
